package model;
// Generated 29/11/2017 14:51:04 by Hibernate Tools 4.3.1



/**
 * TbPreguntas generated by hbm2java
 */
public class TbPreguntas  implements java.io.Serializable {


     private int idPreguntas;
     private TbFormato tbFormato;
     private String descripcion;
     private Boolean estadoPreguntas;

    public TbPreguntas() {
    }

	
    public TbPreguntas(int idPreguntas) {
        this.idPreguntas = idPreguntas;
    }
    public TbPreguntas(int idPreguntas, TbFormato tbFormato, String descripcion, Boolean estadoPreguntas) {
       this.idPreguntas = idPreguntas;
       this.tbFormato = tbFormato;
       this.descripcion = descripcion;
       this.estadoPreguntas = estadoPreguntas;
    }
   
    public int getIdPreguntas() {
        return this.idPreguntas;
    }
    
    public void setIdPreguntas(int idPreguntas) {
        this.idPreguntas = idPreguntas;
    }
    public TbFormato getTbFormato() {
        return this.tbFormato;
    }
    
    public void setTbFormato(TbFormato tbFormato) {
        this.tbFormato = tbFormato;
    }
    public String getDescripcion() {
        return this.descripcion;
    }
    
    public void setDescripcion(String descripcion) {
        this.descripcion = descripcion;
    }
    public Boolean getEstadoPreguntas() {
        return this.estadoPreguntas;
    }
    
    public void setEstadoPreguntas(Boolean estadoPreguntas) {
        this.estadoPreguntas = estadoPreguntas;
    }




}


